### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by Geequlim** [GodotNativeTools/godot_headers#1]
It seems cool for script binding.
But how can I use them?
Where are the definitions of the functions `godot_*`

**Comment by karroffel** [comment]
@Geequlim you need to have a build with the DLScript module. You can build it yourself from [here](https://github.com/bojidar-bg/godot/tree/dlscript-module).

The definitions are in the DLScript module itself. They need to be hidden because those headers describe a C API, the implementations require C++ though. Here's the definition of [`godot_dictionary.h`](https://github.com/bojidar-bg/godot/blob/dlscript-module/modules/dlscript/godot/godot_dictionary.cpp) for example.

-----------------------
# Compiling your library 

> But how can I use them?
I still haven't had the time to create a proper tutorial yet. But basically you need to do this.
 - create a function **with C linkage** `void godot_dlscript_init(godot_dlscript_init_options*)`. This will be the entry point for Godot.

In the `godot_dlscript_init()` function you can use the `godot_script_*` methods (and only there!!).

Then you need to compile your code into a dynamic library.

*example for C*:
 - `clang -c -g -std=c11 -fPIC test.c -I/path/to/godot/headers/ -o test.os`
 - `clang -g -shared test.os -o test.so`

(`-g` is for debugging information)

-------------------
# Using from the editor

Currently you need to *manually create a `DLLibrary` resource and save it as .tres*. This DLLibrary resource contains links to the libraries for the different platform (**only Linux is implemented for now**).

(**^ you need to do this only once**)

Then you just create new 'DLScript's like usual. A `DLScript` resource has a field for the DLLibrary. You can manually set it or leave it empty.
If you leave it empty you can set a default DLLibrary to use in the project settings "dlscript/default_dllibrary".
*Since one library can contain multiple classes you *need* to specify the name of the class you wnat to use*.


Builtin DLScripts work fine as well, I prefer them so you don't have `.dl` files lying around that basically only contain a name.

## That's it!

Now you can just attach new DLScripts to your nodes and run your game like always.

**Comment by Geequlim** [comment]
Thanks for your explanation. it is really cool!

**Comment by Geequlim** [comment]
Is it possible to reuse the code for C-API for anothor script binding like [duktape](http://duktape.org/)?

**Comment by karroffel** [comment]
@Geequlim that would be possible but every method you want to export needs its seperate function pointer. This is a bit problematic/complicated with dynamic languages. If you know what functions you want to export you can create wrapper functions for those (just like I did with my C++ binding).

So yes, it's definitely possible, just questionable how much effort this would require. (With stuff like creating functions at runtime or stuff like that)

**Comment by karroffel** [comment]
@Geequlim Oh, it has been a while, but I extended the API so it's muuuuch easier to integrate something like duktape or Python or whatever. It should be trivial now, without the need of runtime code generation.

To be exact, if you register a method to Godot then you give it a function pointer *and a pointer to some "method data"*. So you can have *one method* that handles **all** methods and just receives the actual method via that method data pointer.

If you have any plans on implementing such a thing feel free to message me on Discord or IRC or somewhere else 😄 

-----

Also there are [demos](https://github.com/GodotNativeTools/GDNative-demos) now, so this can be closed :)

**Comment by Geequlim** [comment]
@karroffel 
I will have a look and try it when I have time.
Thank you!
