### ISSUE TITLE
can i use gdnative in godot3.1

### ISSUE THREAD

**Issue by zhangshiqian1214** [GodotNativeTools/godot_headers#47]
I followed the [official website tutorial ](https://docs.godotengine.org/en/3.1/tutorials/plugins/gdnative/gdnative-c-example.html), step by step, but the debugger reported an error, the error prompt is Attempt to call function 'new' in base 'NativeScript' on a null instance. 
![image](https://user-images.githubusercontent.com/9353330/56875042-bd84f700-6a70-11e9-8263-1126123bcf0a.png)
![image](https://user-images.githubusercontent.com/9353330/56875060-d8f00200-6a70-11e9-8c8c-99a3dba334de.png)
![image](https://user-images.githubusercontent.com/9353330/56875077-f58c3a00-6a70-11e9-9c29-6f1861a4adf6.png)
![image](https://user-images.githubusercontent.com/9353330/56875085-fde47500-6a70-11e9-81e5-259832d1ae3d.png)

**Comment by karroffel** [comment]
I don't know much about windows, but the "Error 193" could be the root cause of this?

https://docs.microsoft.com/en-us/windows/desktop/Debug/system-error-codes--0-499-

![Screenshot_2019-04-29_09-26-11](https://user-images.githubusercontent.com/5209613/56881511-e8674f00-6a60-11e9-937c-0238debb3d3e.png)

Could it be that you are running a 32bit Godot version and compiled a 64 bit dll (or the other way around)?

**Comment by zhangshiqian1214** [comment]
Yes, You are right, Thank you. My Godot is 64bit and i compiled a 32bit dll
![image](https://user-images.githubusercontent.com/9353330/56882257-b02e3380-6a95-11e9-8c3a-e39ee22c320f.png)
