### ISSUE TITLE
Is gdnative_api.json manually ou programmatically generated?

### ISSUE THREAD

**Issue by ricardoalcantara** [GodotNativeTools/godot_headers#58]
I am studying a way to implement the missing built-in methods discussed in this thread. https://github.com/GodotNativeTools/godot-cpp/issues/107

**Comment by sheepandshepherd** [comment]
The JSON is written manually, but not in this repo. It's copied here from `modules/gdnative` in the main Godot repository.

The math functions and similar low-level ones shouldn't be added this way, since the C interface prevents inlining them. It's better to use the ones provided by the binding language's standard library. Some of the others are member functions of the relevant classes (`JSON`, `Dictionary`, `Variant`, ...). There might be a few important ones still missing that would be worth adding though

**Comment by ricardoalcantara** [comment]
I found a easier way, I just clone the engine source and add it to my include path, I tested clamp and Math::angle_lerp and both has worked so far.
